---
#
# 使い方:
#   TARGET_HOST=10.x.x.x
#   MAIN_USERNAME=username
#   MAIN_PASSWORD=password
#   DOCROOT=/var/www/html/htdocs
#   PERMIT_NETWORK=10.0.0.0/8
#   CAKE_ENV_MODE=development
#   env ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i <(echo ${TARGET_HOST}) -u vagrant -k site.yml \
#     --extra-vars "main_username=${MAIN_USERNAME} main_password=`openssl passwd -salt salty -1 ${MAIN_PASSWORD}` docroot=${DOCROOT} permit_network=${PERMIT_NETWORK} cake_env_mode=${CAKE_ENV_MODE}"
# 備考:
#   - TARGET_HOSTは設定対象のホストのIPアドレスを指定してください
#     ユーザvagrantでsshに接続しようとします
#   - MAIN_USERNAMEで指定した名前のユーザ・グループが作成されます
#     パスワードはMAIN_PASSWORDの値になります
#   - DOCROOTで指定したディレクトリがApacheのDocumentRootとなります
#     ディレクトリの所有者・所有グループはMAIN_USERNAMEで指定したものになります
#   - CAKE_ENV_MODEで指定した値が環境変数CAKE_ENV_MODEの値に設定されます
#   - PERMIT_NETWORKで指定したネットワーク範囲からPostgreSQLに接続可能です
#   - PostgreSQLにはID/PASS:postgre/postgresでアクセスできます
#   - 実行後は一度再起動してください
#
- name: for CakePHP on LAPP (Ubuntu 14.04, PostgreSQL 9.3, PHP 5.5) Ver. 20140918
  hosts: all
  sudo: true
  roles:
    - { role: ubuntu1404-common, main_username: "{{ main_username }}", main_password: "{{ main_password }}" }
    - { role: ubuntu1404-apache2, main_username: "{{ main_username }}", docroot: "{{ docroot }}", cake_env_mode: "{{ cake_env_mode }}" }
    - { role: ubuntu1404-php5 }
    - { role: ubuntu1404-postgresql, permit_network: "{{ permit_network }}" }
